version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_URL=localhost:80
    depends_on:
      - frontend

  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=localhost:8080
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
