# Use the official Node.js 16 as a parent image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Install nodemon for development
RUN npm install -g nodemon

# Install any needed packages specified in package.json
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Start app with nodemon
CMD ["nodemon", "-L", "server.js"]
